### PR TITLE
Feature timeline

### PR DESCRIPTION
**Pull request by petterroea**
yeah boy

### CODE REVIEW

**Comment by petterroea** [comment]
pls2not merge yet 2 sec

**Comment by petterroea** [comment]
ok plz2merge

**Comment by petterroea** [comment]
by "mobile friendly" i mean "i disabled animations because touch scroll events are a pain"

**Review by AndreasJJ — COMMENTED** [review]
As mention earlier it's a little funky on small screens (like small phones or really thin resized browsers) other than that it looks good

**Pull request merged**
